name : Deploy Service

on: 
 push:
  branches:
    - main
    - chore/*


jobs:
  docker-build-push:
    runs-on: ubuntu-24.04
    steps:
      # ì†ŒìŠ¤ ê°€ì ¸ì˜¤ê¸°
      - name: Checkout code
        uses: actions/checkout@v4.2.2
        
      # ë””ìŠ¤ì½”ë“œë¡œ ë©”ì„¸ì§€ ì „ì†¡ (Channel 1)
      - name: Start Message (Channel 1)
        # ë¼ì´ë¸ŒëŸ¬ë¦¬ ê°œë°œì/ë¼ì´ë¸ŒëŸ¬ë¦¬ ì´ë¦„@ë²„ì „
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          title: â­Start Deployâ­
          color: 0xF09B59

      - name: run ssh-agent, webfactory/ssh-agent
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # ì›ê²© ì„œë²„ë¥¼ ì‹ íšŒí•  ìˆ˜ ìˆëŠ” ì„œë²„ë¡œ ë“±ë¡í•˜ëŠ” ê³¼ì •
      - name: Add Remote Server Fingerprint to Known Hosts
        run: ssh-keyscan -p ${{ secrets.SSH_PORT }} -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts || true

      - name: Create .env file
        run: |
          echo "# S3" >> .env
          echo "ACCESS_KEY=${{secrets.ACCESS_KEY}}" >> .env
          echo "SECRET_KEY=${{secrets.SECRET_KEY}}" >> .env
          echo "BUCKET_NAME=${{secrets.BUCKET_NAME}}" >> .env
          echo "REGION=${{secrets.REGION}}" >> .env
          echo "# EC2" >> .env
          echo "DOMAIN=${{secrets.DOMAIN}}" >> .env
          echo "API_SERVER=${{secrets.API_SERVER}}" >> .env
          echo "# DB" >> .env
          echo "MYSQL_ROOT_PASSWORD=${{secrets.MYSQL_ROOT_PASSWORD}}" >> .env
          echo "MYSQL_DATABASE=${{secrets.MYSQL_DATABASE}}" >> .env
          echo "# Backend" >> .env
          echo "DATABASE_HOST=${{secrets.DATABASE_HOST}}" >> .env
          echo "DATABASE_PORT=${{secrets.DATABASE_PORT}}" >> .env
          echo "DATABASE_NAME=${{secrets.MYSQL_DATABASE}}" >> .env
          echo "DATABASE_USERNAME=${{secrets.DATABASE_USERNAME}}" >> .env
          echo "DATABASE_PASSWORD=${{secrets.MYSQL_ROOT_PASSWORD}}" >> .env
          echo "JWT_SECRET=${{secrets.JWT_SECRET}}" >> .env
          echo "# Fronted" >> .env
          echo "CLIENT_DOMAIN=${{secrets.DOMAIN}}" >> .env
          echo "CORS_ALLOWED_ORIGIN=https://${{secrets.DOMAIN}}" >> .env
          echo "VITE_API_URL=${{secrets.VITE_API_URL}}" >> .env


      # ìºì‹œ ì €ì¥ ì„¤ì •ì„ ìœ„í•œ actions(ë¼ì´ë¸ŒëŸ¬ë¦¬)
      - name: Set up Cache Repo
        # actions/cache : ê¹ƒí—ˆë¸Œ ìºì‹œ ì €ì¥ì†Œ í™œìš©ì„ ìœ„í•œ ë¼ì´ë¸ŒëŸ¬ë¦¬
        uses: actions/cache@v4.2.0
        with:
        # ìºì‹œë¡œ ê´€ë¦¬í•  ê²½ë¡œ
          path: /tmp/.buildx-cache
          # cacheë¥¼ êµ¬ë¶„í•˜ê¸° ìœ„í•œ ì‹ë³„ì
          # ë¶ˆëŸ¬ì˜¬ ìºì‹œ ì´ë¦„
          # ê°™ì€ ì´ë¦„ìœ¼ë¡œ í•˜ë©´ ìºì‹±ì´ ìœ ì§€ë¨
          key: docker-${{ github.sha }}
          # ë§Œì•½ ìºì‹œ keyë¥¼ ì°¾ì§€ ëª»í•˜ë©´ ì‹¤í–‰í•  keyì˜ íŒ¨í„´
          restore-keys: |
            docker- 


      # ìºì‹œ ê´€ë¦¬ ë¼ì´ë¸ŒëŸ¬ë¦¬ 
      - name: Set up Docker Buildkit
        uses: docker/setup-buildx-action@v3

        # ë¹Œë” ì‚¬ìš©
      - name: Create Buildkit Builder
        run: |
          docker buildx create --use --name buildkit

      - name: Docker Image Build
        # run: docker compose build
        run: docker compose build --build-arg BUILDKIT_INLINE_CACHE=1


      - name: Login DockerHub
        run: echo '${{ secrets.DOCKER_PASSWORD }}' | docker login -u '${{ secrets.DOCKER_USERNAME }}' --password-stdin
      
      - name: Docker Image Push
        run: docker compose push

      - name: Copy .env / docker-compose.yml
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "docker-compose.yml, .env"
          target: "~/work-directory"
          
      - name: Pull Image & Up Container
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ~/work-directory
            docker compose pull
            docker compose down
            docker compose up -d
            docker system prune -f
            
      # Discord ì•Œë¦¼ - ë°°í¬ ì„±ê³µ
      - name: Discord Notification - Success
        if: success()
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          title: "ğŸŒ Success Deploy ğŸŒ"
          description: |
            Repository: ${{ github.repository }}
            Branch: ${{ github.ref_name }}
            Commit: ${{ github.event.head_commit.message }}
          color: 0x75F94D
      
      # Discord ì•Œë¦¼ - ë°°í¬ ì‹¤íŒ¨
      - name: Discord Notification - Failure
        if: failure()
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          title: "ğŸ˜­ Failure Deploy ğŸ˜­"
          description: |
            Repository: ${{ github.repository }}
            Branch: ${{ github.ref_name }}
            Commit: ${{ github.event.head_commit.message }}
          color: 0xEA3680